"""empty message

Revision ID: 904aba4b5a96
Revises: 
Create Date: 2017-11-21 08:54:53.552616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904aba4b5a96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_authors', sa.Column('email', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'tbl_authors', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_authors', type_='unique')
    op.drop_column('tbl_authors', 'email')
    # ### end Alembic commands ###
