"""empty message

Revision ID: 3994efd4962e
Revises: 9f8956c525ad
Create Date: 2017-11-21 09:14:17.545040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3994efd4962e'
down_revision = '9f8956c525ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_authors', sa.Column('id_card', sa.String(length=18), nullable=True))
    op.create_unique_constraint("id_card", 'tbl_authors', ['id_card'])
    op.add_column('tbl_books', sa.Column('leader', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_books', 'leader')
    op.drop_constraint('id_card', 'tbl_authors', type_='unique')
    op.drop_column('tbl_authors', 'id_card')
    # ### end Alembic commands ###
