"""add mobile

Revision ID: 9f8956c525ad
Revises: 904aba4b5a96
Create Date: 2017-11-21 08:57:38.949027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8956c525ad'
down_revision = '904aba4b5a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_authors', sa.Column('mobile', sa.String(length=11), nullable=True))
    op.create_unique_constraint("mobile", 'tbl_authors', ['mobile'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("mobile", 'tbl_authors', type_='unique')
    op.drop_column('tbl_authors', 'mobile')
    # ### end Alembic commands ###
